### ISSUE TITLE
Illegal instruction (core dumped) on Ubuntu

### ISSUE THREAD

**Issue by joanneroll** [nmandery/h3ronpy#39]
Hi Nico, 

when attempting to execute the module, the core dumps due to illegal instruction. (Possibly related to #26)

```
>>> import geopandas as gpd
>>> from h3ronpy.pandas.vector import geodataframe_to_cells
>>> shape = gpd.read_file("admin_bavaria.gpkg")
>>> shape
     GID_1 GID_0  COUNTRY  NAME_1 VARNAME_1 NL_NAME_1     TYPE_1   ENGTYPE_1 CC_1 HASC_1  ISO_1  area_adm1                                           geometry
0  DEU.2_1   DEU  Germany  Bayern   Bavaria        NA  Freistaat  Free State   09  DE.BY  DE-BY  70531.935  MULTIPOLYGON (((8.92500 50.10593, 8.92493 50.1...
>>> df = geodataframe_to_cells(shape,3)
Illegal instruction (core dumped)
```

I'm using `h3ronpy version 0.19.1` and installed it with `pip version 22.0.2`. The OS is Ubuntu:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
```

However, when installing the package from source, the error does not occur. 

Do you have an idea how to fix this issue when using `pip install`? 

Best, 
Johanna

**Comment by nmandery** [comment]
Hi Johanna,

knowing the hardware you are probably using to run h3ronpy, the reason is that CPU does not support the quite common AVX and FMA instruction sets. After a few other projects like polars started to distribute wheel compiled with these instruction sets, I decided to do the same as using these instructions gave a nice performance boost. The instruction sets are fairly old at this point and supported on most machines. Runtime-detection of CPU features - like numpy does - is sadly out of scope.

In your case you can not use the wheels from pypi as they are build using these flags (see https://github.com/nmandery/h3ronpy/blob/7cc58775110fada7fb3b576901b9664ae2ff902e/.github/workflows/ci.yml#L40). You can either use another machine (geofarm is fine for example) or compile h3ronpy yourself.

I suppose you are using a container - you could use a multistage build process and compile h3ronpy in its own stage and copy the wheel to your install-stage. I can provide you a snippet for this stage in that case.

Sorry for the inconvenience ;) 

Best,
Nico

**Comment by joanneroll** [comment]
![grafik](https://github.com/nmandery/h3ronpy/assets/61839407/91cd44e9-b2b8-4bba-8a2a-338d9a2490d3)
